apiVersion: v1
kind: ConfigMap
metadata:
  name: quake3-server-config
data:
  config.yaml: |
    fragLimit: 25
    timeLimit: 15m
    bot:
      minPlayers: 3
    game:
      motd: "Welcome to Quake 3 on OpenShift"
      type: FreeForAll
      forceRespawn: false
      inactivity: 10m
      quadFactor: 3
      weaponRespawn: 3
    server:
      hostname: "quakekube"
      maxClients: 12
      password: "$(pwgen -n 16 1)"
    commands:
      - addbot sarge 2
    maps:
    - name: q3dm17
      type: FreeForAll
      timeLimit: 10m