apiVersion: cdi.kubevirt.io/v1beta1
kind: DataVolume
metadata:
  name: freebsd-14.2
  namespace: openshift-virtualization-os-images
  annotations:
    cdi.kubevirt.io/storage.bind.immediate.requested: 'true'
spec:
  source:
    http:
      # see https://bsd-cloud-image.org/
      url: https://object-storage.public.mtl1.vexxhost.net/swift/v1/1dbafeefbd4f4c80864414a441e72dd2/bsd-cloud-image.org/images/freebsd/14.2/2024-12-08/zfs/freebsd-14.2-zfs-2024-12-08.qcow2
  storage:
    resources:
      requests:
        storage: 30Gi